apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: happylife
type: Opaque
stringData:
  # IMPORTANT: Update this with your actual Azure Document Intelligence API Key
  AZURE_DOC_INTEL_API_KEY: "5GbUl0ETJdY008l0etsEDH6mNDubvDAXUsNpudoNppMwDBRZ3IJZJQQJ99BKAC5RqLJXJ3w3AAALACOG9VZG"
