apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: happylife

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - app-secret.yaml
  - app-configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - webapp-deployment.yaml
  - webapp-service.yaml

# Common labels applied to all resources
commonLabels:
  project: happylife
  managed-by: kustomize
