apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: happylife
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: HappyLifeDb
  MYSQL_USER: happylife
  MYSQL_PASSWORD: happylife
